name: Deploy docs

on:
  push:
    branches: [main]
    paths:
      - "**.ts"
      - "**.json"
      - "**.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install deps
        run: yarn install
      - name: Build docs
        run: yarn docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
